package elr.gui.tabs;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JFrame;

/**
 *
 * @author Infernage
 */
public class Changelog extends javax.swing.JPanel{
    private final String url = "https://dl.dropbox.com/s/1mao7aijte275ls/Changelog.txt?dl=1";
    private final JFrame frame;
    
    /**
     * Creates new form Changelog
     */
    public Changelog(JFrame f) {
        frame = f;
        initComponents();
        initChangelog();
    }
    
    private void initChangelog(){
        StringBuilder builder = new StringBuilder();
        try {
            HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
            connection.setRequestMethod("GET");
            try (BufferedReader bf = new BufferedReader(new InputStreamReader(connection.getInputStream(),
                    "iso-8859-1"))) {
                String line = bf.readLine();
                while(line != null){
                    builder.append('\n').append(line);
                    line = bf.readLine();
                }
            }
        } catch (Exception e) {
            builder.delete(0, builder.length());
            builder.append("Failed to load changelog.\nReason: ").append(e.toString());
        }
        changelog.setText(builder.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        changelog = new javax.swing.JTextArea();

        changelog.setEditable(false);
        changelog.setColumns(20);
        changelog.setLineWrap(true);
        changelog.setRows(5);
        changelog.setWrapStyleWord(true);
        jScrollPane1.setViewportView(changelog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea changelog;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
