/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MLR.gui;

import MLR.InnerApi;
import java.io.FileOutputStream;

/**
 *
 * @author Reed
 */
public class Options extends javax.swing.JDialog {

    /**
     * Creates new form Options
     */
    public Options(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        loadConfig();
    }
    public void saveConfig(){
        int ram = jComboBox1.getSelectedIndex();
        switch (ram){
            case 0: InnerApi.configuration.setProperty("maxRAM", "512");
                break;
            case 1: InnerApi.configuration.setProperty("maxRAM", "1024");
                break;
            case 2: InnerApi.configuration.setProperty("maxRAM", "2048");
                break;
            case 3: InnerApi.configuration.setProperty("maxRAM", "3072");
                break;
            case 4: InnerApi.configuration.setProperty("maxRAM", "4096");
                break;
            case 5: InnerApi.configuration.setProperty("maxRAM", "5120");
                break;
            case 6: InnerApi.configuration.setProperty("maxRAM", "6144");
                break;
        }
        if (jCheckBox1.isSelected()){
            InnerApi.configuration.setProperty("systemProxy", "true");
        } else{
            InnerApi.configuration.setProperty("systemProxy", "false");
        }
        if (jCheckBox2.isSelected()){
            InnerApi.configuration.setProperty("defaultPath", "true");
            InnerApi.configuration.setProperty("installPath", "default");
        } else{
            InnerApi.configuration.setProperty("defaultPath", "false");
            InnerApi.configuration.setProperty("installPath", jTextField1.getText());
        }
        if (jCheckBox4.isSelected()){
            InnerApi.configuration.setProperty("consoleActivated", "false");
            InnerApi.configuration.setProperty("consoleMinimized", "false");
        } else{
            InnerApi.configuration.setProperty("consoleActivated", "true");
            if (jCheckBox3.isSelected()){
                InnerApi.configuration.setProperty("consoleMinimized", "true");
            } else{
                InnerApi.configuration.setProperty("consoleMinimized", "false");
            }
        }
        if (InnerApi.Init.mainGUI.jCheckBox1.isSelected()){
            InnerApi.configuration.setProperty("rememberUser", "true");
        } else{
            InnerApi.configuration.setProperty("rememberUser", "false");
        }
        if (InnerApi.Init.mainGUI.jCheckBox2.isSelected()){
            InnerApi.configuration.setProperty("rememberPassword", "true");
        } else{
            InnerApi.configuration.setProperty("rememberPassword", "false");
        }
        try {
            FileOutputStream out = new FileOutputStream(InnerApi.Files.config());
            InnerApi.configuration.store(out, "Options MLR");
            out.close();
        } catch (Exception e) {
            InnerApi.Init.error.setError(e);
        }
        InnerApi.Init.reloadPath();
    }
    public void loadConfig(){
        int ram = Integer.parseInt(InnerApi.configuration.getProperty("maxRAM"));
        switch (ram){
            case 512: jComboBox1.setSelectedItem("512Mb");
                break;
            case 1024: jComboBox1.setSelectedItem("1Gb");
                break;
            case 2048: jComboBox1.setSelectedItem("2Gb");
                break;
            case 3072: jComboBox1.setSelectedItem("3Gb");
                break;
            case 4096: jComboBox1.setSelectedItem("4Gb");
                break;
            case 5120: jComboBox1.setSelectedItem("5Gb");
                break;
            case 6144: jComboBox1.setSelectedItem("6Gb");
                break;
        }
        jCheckBox1.setSelected(InnerApi.configuration.getProperty("systemProxy").equals("true"));
        boolean defaul = InnerApi.configuration.getProperty("defaultPath").equals("true");
        jCheckBox2.setSelected(defaul);
        jCheckBox2ActionPerformed(null);
        if (!defaul){
            jTextField1.setText(InnerApi.configuration.getProperty("installPath"));
        }
        defaul = InnerApi.configuration.getProperty("consoleActivated").equals("true");
        if (!defaul){
            jCheckBox4.setSelected(true);
        } else{
            jCheckBox4.setSelected(false);
            if (InnerApi.configuration.getProperty("consoleMinimized").equals("true")){
                jCheckBox3.setSelected(true);
            } else{
                jCheckBox3.setSelected(false);
            }
        }
        jCheckBox4ActionPerformed(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("RAM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Opciones");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Proxy");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Carpeta de instalación");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "512Mb", "1Gb", "2Gb", "3Gb", "4Gb", "5Gb", "6Gb" }));

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Usar proxy del sistema operativo");

        jTextField1.setText("Default");
        jTextField1.setEnabled(false);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Ruta por defecto");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Consola");

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Mostrar minimizada");

        jCheckBox4.setText("No mostrar");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox2)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox3)
                                .addGap(10, 10, 10)
                                .addComponent(jCheckBox4)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4))
                .addGap(7, 7, 7)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()){
            jTextField1.setText("Default");
            jTextField1.setEnabled(false);
        } else{
            jTextField1.setText("");
            jTextField1.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox4.isSelected()){
            jCheckBox3.setSelected(false);
            jCheckBox3.setEnabled(false);
        } else{
            jCheckBox3.setEnabled(true);
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        loadConfig();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        saveConfig();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
